# Generated by Django 2.0.5 on 2021-10-07 19:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(max_length=150, verbose_name='Доклад')),
            ],
            options={
                'verbose_name': 'Добавление доклада',
                'verbose_name_plural': 'Добавление доклада',
            },
        ),
        migrations.CreateModel(
            name='RegistrationGuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('surname', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Регистрация гостя',
                'verbose_name_plural': 'Регистрация гостя',
            },
        ),
        migrations.CreateModel(
            name='RegistrationSpiker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('surname', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('phoneNumber', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('password', models.CharField(max_length=150, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Регистрация спикера',
                'verbose_name_plural': 'Регистрация спикера',
            },
        ),
    ]
