# Generated by Django 3.2.8 on 2022-11-23 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20221121_2137'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
